name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python 3.11
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --python 3.11

      - name: Build exe
        run: uv run poe build-exe

      - name: Rename
        run: ren dist\palworld-monitor.exe palworld-monitor-windows.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: palworld-monitor-win64
          path: dist/palworld-monitor-windows.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python 3.11
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --python 3.11

      - name: Build binary
        run: uv run poe build-exe

      - name: Rename
        run: mv dist/palworld-monitor dist/palworld-monitor-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: palworld-monitor-linux64
          path: dist/palworld-monitor-linux

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: palworld-monitor-win64

      - uses: actions/download-artifact@v4
        with:
          name: palworld-monitor-linux64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            palworld-monitor-windows.exe
            palworld-monitor-linux
          generate_release_notes: true
